const express = require("express");
const cors = require("cors");
const nodemailer = require("nodemailer");
const admin = require("firebase-admin");

const app = express();
app.use(cors());
app.use(express.json());

/* ================= FIREBASE SETUP ================= */

const serviceAccount = require("./serviceAccountKey.json");

admin.initializeApp({
  credential: admin.credential.cert(serviceAccount)
});

const db = admin.firestore();

/* ================= EMAIL SETUP ================= */

const transporter = nodemailer.createTransport({
  host: "smtp.gmail.com",
  port: 587,
  secure: false,
  auth: {
    user: "penugondasrimoulikrishna2008@gmail.com",
    pass: "ojezebvfxexykzbi"
  },
  tls: {
    rejectUnauthorized: false
  }
});

/* ================= EMAIL FUNCTION ================= */

function sendMail(name, amount, decision, email) {
  console.log("Sending mail to:", email);

  const mailOptions = {
    from: "penugondasrimoulikrishna2008@gmail.com",
    to: email,
    subject: "Quantum Risk Report 📊",
    text: `Stock: ${name}
Amount: ${amount}

Decision: ${decision}

Generated by Quantum Risk Analyzer`
  };

  transporter.sendMail(mailOptions, (err, info) => {
    if (err) {
      console.log("MAIL ERROR:", err);
    } else {
      console.log("Email sent:", info.response);
    }
  });
}

/* ================= ROUTES ================= */

// ➕ Add stock (Firebase lo save)
app.post("/add", async (req, res) => {
  const { name, amount, email } = req.body;

  await db.collection("stocks").add({
    name,
    amount,
    email
  });

  res.json({ message: "Saved in Firebase" });
});

// 📊 Risk + Email
app.get("/risk", async (req, res) => {

  let scenarios = 100;
  let results = [];

  for (let i = 0; i < scenarios; i++) {
    let change = (Math.random() - 0.5) * 20;
    results.push(change);
  }

  let worst = Math.min(...results);
  let avg = results.reduce((a, b) => a + b, 0) / scenarios;

  let decision = avg > 0 && worst > -10 ? "BUY" : "AVOID";

  // 🔥 Latest stock Firebase nunchi tisukovali
  let snapshot = await db.collection("stocks")
    .limit(1)
    .get();

  let latestStock = null;

  snapshot.forEach(doc => {
    latestStock = doc.data();
  });

  // 🔥 Email send
  if (latestStock) {
    sendMail(
      latestStock.name,
      latestStock.amount,
      decision,
      latestStock.email
    );
  }

  res.json({
    risk: worst.toFixed(2),
    return: avg.toFixed(2),
    decision: decision
  });
});

/* ================= SERVER ================= */

app.listen(3000, () => {
  console.log("Server running on http://localhost:3000");
});
