
const nodemailer = require("nodemailer");
const express = require("express");
const cors = require("cors");

const app = express();
app.use(cors());
app.use(express.json());

/* ================= EMAIL SETUP ================= */

const transporter = nodemailer.createTransport({
  host: "smtp.gmail.com",
  port: 587,
  secure: false,
  auth: {
    user: "penugondasrimoulikrishna2008@gmail.com",
    pass: "ojezebvfxexykzbi"
  },
  tls: {
    rejectUnauthorized: false
  }
});

/* ================= EMAIL FUNCTION ================= */

function sendMail(name, amount, decision, email) {
  console.log("Sending mail to:", email);

  const mailOptions = {
    from: "penugondasrimoulikrishna2008@gmail.com",
    to: email, // 🔥 USER EMAIL
    subject: "Quantum Risk Report 📊",
    text: `Stock: ${name}
Amount: ${amount}

Decision: ${decision}

Generated by Quantum Risk Analyzer`
  };

  transporter.sendMail(mailOptions, (err, info) => {
    if (err) {
      console.log("MAIL ERROR:", err);
    } else {
      console.log("Email sent:", info.response);
    }
  });
}

/* ================= DATABASE ================= */

let portfolio = [];

/* ================= ROUTES ================= */

// ➕ Add stock (with email)
app.post("/add", (req, res) => {
  const { name, amount, email } = req.body;

  console.log("Received:", name, amount, email); // 🔥 DEBUG

  portfolio.push({ name, amount, email });

  res.json({ message: "Added", portfolio });
});

// 📊 Get portfolio
app.get("/portfolio", (req, res) => {
  res.json(portfolio);
});

// ⚡ Risk + Decision + Email
app.get("/risk", (req, res) => {

  let scenarios = 100;
  let results = [];

  for (let i = 0; i < scenarios; i++) {
    let change = (Math.random() - 0.5) * 20;
    results.push(change);
  }

  let worst = Math.min(...results);
  let avg = results.reduce((a, b) => a + b, 0) / scenarios;

  // 🔥 Decision logic
  let decision = "";

  if (avg > 0 && worst > -10) {
    decision = "BUY";
  } else {
    decision = "AVOID";
  }

  // 🔥 Get latest stock
  let latestStock = portfolio[portfolio.length - 1];

  console.log("Latest Stock:", latestStock); // 🔥 DEBUG

  // 🔥 Send email to USER
  if (latestStock && latestStock.email) {
    sendMail(
      latestStock.name,
      latestStock.amount,
      decision,
      latestStock.email
    );
  }

  res.json({
    risk: worst.toFixed(2),
    return: avg.toFixed(2),
    decision: decision
  });
});

/* ================= SERVER ================= */

app.listen(3000, () => {
  console.log("Server running on http://localhost:3000");
});
